name: Automate Preprocessing

on:
  workflow_dispatch:
  push:
    paths:
      - 'preprocessing/automate.py'
      - 'HeartDiagnosa_raw.csv'
      - 'requirements.txt'

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automate.py
        run: |
          python preprocessing/automate.py
